config/routes.rb
Rails.application.routes.draw do
  root "user_registrations#index"
  resources :user_registrations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_registrations_controller.rb
class UserRegistrationsController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user_registration_form = UserRegistrationForm.new
  end

  def create
    @user_registration_form = UserRegistrationForm.new(user_registration_form_params)

    if @user_registration_form.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

    def user_registration_form_params
      params.require(:user_registration_form).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_registrations_helper.rb
module UserRegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormObjectTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_registrations/index.html.erb
<div class="wrapper">
  <div class="btn">
    <%= link_to '登録する', new_user_registration_path %>
  </div>
  <div class="formats">
    <% @users.each do |user| %>
      <div class="name">ユーザー情報：<%= user.name %></div>
      <div class="name">住所情報：<%= user.address%></div>
    <% end %>
  </div>
</div>

app/views/user_registrations/new.html.erb
<%= form_with(model: @user_registration_form, url: user_registrations_path, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <div class="actions">
    <%= form.submit "登録する" %>
  </div>
<% end %>